#!/usr/bin/env python3
"""Remoroo Studio — local server (Python; bundled with the CLI).

Serves the prebuilt SPA (dist/) over the LAN with a per-launch token, does the
project IO (cell.json + the remoroo_cell/ export + git commit), and reverse-
proxies the data planes to the REAL edge/brain when configured. The simulators
are entirely CLIENT-SIDE (the SPA's DispatchEdge falls back to SimEdge when
/health reports edge:"sim"), so this server needs no sim code and the robot
computer needs only Python — no Node at runtime.

    DIST=/path/to/dist PROJECT=/path/to/repo PORT=7777 TOKEN=… \
    [EDGE_URL=http://127.0.0.1:7779] [BRAIN_URL=https://…] python studio_server.py
"""
from __future__ import annotations

import io
import json
import os
import shutil
import socket
import subprocess
import tempfile
import zipfile
from http.client import HTTPConnection, HTTPSConnection, IncompleteRead
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlsplit, urlparse, parse_qs

HERE = Path(__file__).resolve().parent
DIST = Path(os.environ.get("DIST", HERE.parent / "dist")).resolve()
PROJECT = Path(os.environ.get("PROJECT", HERE.parent / "project")).resolve()
PORT = int(os.environ.get("PORT", "7777"))
TOKEN = os.environ.get("TOKEN", os.urandom(8).hex())
EDGE_URL = os.environ.get("EDGE_URL", "").rstrip("/")
BRAIN_URL = os.environ.get("BRAIN_URL", "").rstrip("/")  # the control plane (run API + agent)
RUN_ID = os.environ.get("RUN_ID", "")  # the @robot_setup run the browser attaches to
SESSION_KEY = os.environ.get("SESSION_KEY", "")  # auth for the CP run API (browser never sees it)
_STALE_RUNS_SEEN: set = set()  # stale run ids already logged (so a retrying tab logs once)

MIME = {
    ".html": "text/html", ".js": "text/javascript", ".mjs": "text/javascript",
    ".css": "text/css", ".json": "application/json", ".svg": "image/svg+xml",
    ".png": "image/png", ".jpg": "image/jpeg", ".glb": "model/gltf-binary",
    ".stl": "model/stl", ".urdf": "application/xml", ".wasm": "application/wasm",
    ".ico": "image/x-icon", ".map": "application/json",
}


def lan_ip() -> str:
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return "localhost"


def _cookie_token(headers) -> str:
    """Read the studio auth cookie (set when the SPA is opened with a valid token)."""
    for part in (headers.get("Cookie") or "").split(";"):
        part = part.strip()
        if part.startswith("rs_token="):
            return part[len("rs_token="):]
    return ""


def auth_reason(query: dict, headers):
    """Return (ok, info). Accept the token via ?token= (launch URL), a Bearer
    header, OR the rs_token cookie. `info` is which method matched, or — on
    failure — exactly what was present, so a 401 is never a mystery."""
    q = (query.get("token") or [""])[0]
    auth = (headers.get("Authorization") or "").replace("Bearer ", "")
    ck = _cookie_token(headers)
    if q == TOKEN:
        return True, "query"
    if auth == TOKEN:
        return True, "bearer"
    if ck == TOKEN:
        return True, "cookie"
    return False, {"query_present": bool(q), "cookie_present": bool(ck), "bearer_present": bool(auth)}


def token_ok(query: dict, headers) -> bool:
    return auth_reason(query, headers)[0]


def _pre(s: str) -> str:
    return (s[:4] + "…") if s else "∅"


def git_commit(repo: Path, rel: str) -> bool:
    try:
        subprocess.run(["git", "-C", str(repo), "rev-parse", "--is-inside-work-tree"], check=True, capture_output=True)
        subprocess.run(["git", "-C", str(repo), "add", rel], check=True, capture_output=True)
        subprocess.run(["git", "-C", str(repo), "commit", "-m", "remoroo setup: cell bundle"], check=True, capture_output=True)
        return True
    except Exception:
        return False


def _tolerant_yaml_load(text: str):
    """Load a YAML that may carry python/numpy tags (a file written with `yaml.dump` of np.float32
    instead of `safe_dump` of python floats) — `safe_load` raises on those. The file is LOCALLY
    generated by the agent (trusted), so `unsafe_load` is acceptable and reconstructs the numpy/
    python scalars cleanly. If that's unavailable, fall back to a loader that IGNORES unknown tags."""
    import yaml

    try:
        return yaml.unsafe_load(text) or {}                   # recovers numpy/python-tagged scalars
    except Exception:
        pass

    class _Loader(yaml.SafeLoader):
        pass

    def _ignore_unknown(loader, tag_suffix, node):
        if isinstance(node, yaml.ScalarNode):
            return loader.construct_scalar(node)
        if isinstance(node, yaml.SequenceNode):
            return loader.construct_sequence(node, deep=True)
        return loader.construct_mapping(node, deep=True)

    _Loader.add_multi_constructor("", _ignore_unknown)        # tag:yaml.org,... and !python/...
    return yaml.load(text, Loader=_Loader) or {}


def _find_collision_spheres(obj) -> dict:
    """Find the `collision_spheres` mapping (link -> [sphere,...]) at ANY depth — the agent's file may
    nest it under robot_cfg.kinematics, at the top level, or elsewhere depending on how it built it."""
    if isinstance(obj, dict):
        cs = obj.get("collision_spheres")
        if isinstance(cs, dict) and cs:
            return cs
        for v in obj.values():
            found = _find_collision_spheres(v)
            if found:
                return found
    return {}


def _sphere_center_radius(s):
    """One sphere → (center[3], radius) | (None, None). Accepts the dict form
    `{center:[x,y,z], radius:r}` AND the flat-list form `[x, y, z, r]`."""
    try:
        if isinstance(s, dict):
            c, r = s.get("center"), s.get("radius")
        elif isinstance(s, (list, tuple)) and len(s) >= 4:
            c, r = s[:3], s[3]
        else:
            return None, None
        if c is not None and r is not None and len(c) >= 3:
            return [float(c[0]), float(c[1]), float(c[2])], float(r)
    except (TypeError, ValueError):
        pass
    return None, None


class Handler(BaseHTTPRequestHandler):
    server_version = "RemorooStudio/1.0"

    def log_message(self, *a):
        pass

    # ---- helpers ----
    def _json(self, obj, code=200):
        data = json.dumps(obj).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def _proxy(self, base: str, auth: str = ""):
        u = urlsplit(base)
        cls = HTTPSConnection if u.scheme == "https" else HTTPConnection
        conn = cls(u.hostname, u.port or (443 if u.scheme == "https" else 80), timeout=600)
        length = int(self.headers.get("Content-Length", "0") or 0)
        body = self.rfile.read(length) if length else None
        headers = {k: v for k, v in self.headers.items() if k.lower() not in ("host", "connection", "content-length")}
        if auth:  # inject the CP session key; the browser never holds it
            headers["Authorization"] = f"Bearer {auth}"
        if body is not None:
            headers["Content-Length"] = str(len(body))
        try:
            conn.request(self.command, self.path, body=body, headers=headers)
            resp = conn.getresponse()
        except Exception as e:
            self._json({"error": "upstream unreachable", "detail": str(e)}, 502)
            return
        self.send_response(resp.status)
        for k, v in resp.getheaders():
            if k.lower() in ("transfer-encoding", "connection", "content-length"):
                continue
            self.send_header(k, v)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()  # close-delimited (HTTP/1.0) — streams SSE fine
        try:
            while True:
                # read1() returns as soon as ANY data is available; plain read(n)
                # blocks until n bytes accumulate, which buffers small SSE events
                # in the proxy and makes the live agent feed look frozen.
                chunk = resp.read1(65536)
                if not chunk:
                    break
                self.wfile.write(chunk)
                self.wfile.flush()
        except (BrokenPipeError, ConnectionResetError):
            pass  # the BROWSER hung up — normal SSE teardown
        except (IncompleteRead, ValueError, OSError):
            # The UPSTREAM (control plane) ended the chunked SSE without a clean
            # terminating chunk — run finished, LB/idle timeout, or CP reconnect.
            # For a long-lived stream that's a normal end-of-stream, not an error;
            # the browser's EventSource just reconnects. Don't let it escape do_GET
            # and spam ThreadingHTTPServer with an IncompleteRead traceback.
            pass
        finally:
            conn.close()

    def _static(self, path: str, query: dict | None = None):
        rel = "index.html" if path == "/" else path.lstrip("/")
        f = (DIST / rel)
        if not f.exists() or f.is_dir():
            f = DIST / "index.html"  # SPA fallback
        if not f.exists():
            self.send_response(404); self.end_headers(); self.wfile.write(b"Not built. Run the studio build.")
            return
        data = f.read_bytes()
        # INJECT THE TOKEN into the SPA's HTML so the client ALWAYS has it — no
        # matter how the page was opened (bare IP, bookmark, no ?token=). This is
        # the definitive fix for the recurring "query=∅ cookie=∅" 401s: the token
        # ships WITH the page that asks for it, instead of relying on the operator's
        # URL/cookie carrying it. (The studio is on the robot's LAN; anyone who can
        # load the page is already on it.)
        if f.suffix == ".html":
            tag = f"<script>window.__RS_TOKEN__={json.dumps(TOKEN)};</script>".encode()
            data = data.replace(b"</head>", tag + b"</head>", 1) if b"</head>" in data else tag + data
        self.send_response(200)
        self.send_header("Content-Type", MIME.get(f.suffix, "application/octet-stream"))
        self.send_header("Content-Length", str(len(data)))
        if query and (query.get("token") or [""])[0] == TOKEN:
            self.send_header("Set-Cookie", f"rs_token={TOKEN}; Path=/; SameSite=Lax; Max-Age=2592000")
        self.end_headers()
        self.wfile.write(data)

    # ---- project IO ----
    def _project(self, path: str, query: dict):
        ok, info = auth_reason(query, self.headers)
        if not ok:
            # GROUND TRUTH: log exactly why auth failed (to the `remoroo setup`
            # terminal) + return it to the UI so a 401 is never a guessing game.
            qtok = (query.get("token") or [""])[0]
            print(
                f"[studio-auth] 401 {self.command} {path} — {info} · "
                f"query={_pre(qtok)} cookie={_pre(_cookie_token(self.headers))} "
                f"expected={_pre(TOKEN)}",
                flush=True,
            )
            none_present = isinstance(info, dict) and not any(info.values())
            self._json({
                "error": "token required",
                "reason": "no_token_sent" if none_present else "token_mismatch",
                "got": info,
                "hint": "Open the Studio via the exact URL the CLI printed (with ?token=…). "
                        "If you just restarted setup, reopen that fresh URL.",
            }, 401)
            return
        cell_path = PROJECT / "cell.studio.json"
        if path == "/project/cell" and self.command == "GET":
            if not cell_path.exists():
                self._json({"error": "no project"}, 404)
                return
            self._json(json.loads(cell_path.read_text()))
            return
        if path == "/project/cell" and self.command == "PUT":
            PROJECT.mkdir(parents=True, exist_ok=True)
            length = int(self.headers.get("Content-Length", "0") or 0)
            cell_path.write_bytes(self.rfile.read(length))
            self._json({"ok": True, "path": str(cell_path)})
            return
        # cell.yaml — the canonical RobotModel inputs the operator authors at G0.
        # Stored verbatim (the SPA sends YAML text) so the edge/agent read it as-is.
        yaml_path = PROJECT / "remoroo_cell" / "cell.yaml"
        if path == "/project/cellyaml" and self.command == "GET":
            if not yaml_path.exists():
                self._json({"error": "no cell.yaml"}, 404)
                return
            text = yaml_path.read_bytes()
            self.send_response(200)
            self.send_header("Content-Type", "text/yaml")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Content-Length", str(len(text)))
            self.end_headers()
            self.wfile.write(text)
            return
        if path == "/project/cellyaml" and self.command == "PUT":
            yaml_path.parent.mkdir(parents=True, exist_ok=True)
            length = int(self.headers.get("Content-Length", "0") or 0)
            yaml_path.write_bytes(self.rfile.read(length))
            self._json({"ok": True, "path": str(yaml_path)})
            return
        # Gate completion = real artifact presence under remoroo_cell/ (the setup
        # output contract). The SPA polls this to drive the G0–G9 rail — no sim.
        if path == "/project/artifacts" and self.command == "GET":
            cell = PROJECT / "remoroo_cell"
            has = lambda *rels: any((cell / r).exists() for r in rels)
            self._json({
                "detect": has("cell.yaml"),
                "toolchain": has("requirements.lock"),
                "bridge": has("primitives.py"),
                "calibrate": has("calibration/report.md", "calibration/hand_eye.yaml"),
                "spheres": has("robot_model/collision_spheres.yml"),
                "model": has("robot_model/robot.urdf"),
                "capture": has("capture/schema.json", "capture/sample_episode"),
                "signoff": has("setup_report.md"),
            })
            return
        # The PERSISTED gate state machine — the single source of truth for setup
        # progress, read by both the Studio (boot hydration; survives refresh /
        # reconnect / process death) and the agent (on `remoroo setup --continue`,
        # so it resumes deterministically instead of re-deriving from the repo).
        state_path = PROJECT / "remoroo_cell" / "setup_state.json"
        if path == "/project/setup_state" and self.command == "GET":
            if not state_path.exists():
                self._json({})  # nothing persisted yet
                return
            try:
                self._json(json.loads(state_path.read_text()))
            except Exception:
                self._json({})
            return
        if path == "/project/setup_state" and self.command in ("PUT", "POST"):
            # POST is accepted too so navigator.sendBeacon (flush-on-close, POST-only)
            # can persist the final state when the operator closes the tab.
            state_path.parent.mkdir(parents=True, exist_ok=True)
            length = int(self.headers.get("Content-Length", "0") or 0)
            body = self.rfile.read(length)
            # RUN-SCOPED GUARD: setup_state.json is one file per project dir, but several
            # studio tabs — including STALE ones from prior `remoroo setup` runs still open
            # and reconnecting — can all PUT to it and clobber the LIVE run's state machine,
            # which the agent then reads as a phantom "resume". Only the CURRENT run (RUN_ID)
            # may write it; a write tagged with any other (or no) run_id is a stale tab → drop.
            import json as _json
            try:
                body_run = _json.loads(body).get("run_id")
            except Exception:
                body_run = None
            if RUN_ID and body_run != RUN_ID:
                self._json({"ok": False, "rejected": "stale_run", "current": RUN_ID}, 409)
                return
            state_path.write_bytes(body)
            self._json({"ok": True, "path": str(state_path)})
            return
        # Read REAL artifacts back so a resume/refresh shows actual progress, not an
        # empty stage: the cuRobo collision spheres.
        if path == "/project/spheres" and self.command == "GET":
            f = PROJECT / "remoroo_cell" / "robot_model" / "collision_spheres.yml"
            if not f.exists():
                self._json({"spheres": []}); return
            try:
                import yaml  # type: ignore
                text = f.read_text()
                try:
                    data = yaml.safe_load(text) or {}
                except yaml.YAMLError:
                    data = _tolerant_yaml_load(text)          # survive numpy/python-tagged dumps
                cs = _find_collision_spheres(data)            # search any nesting
                out, skipped = [], 0
                for link, arr in (cs or {}).items():
                    for s in (arr or []):
                        c, r = _sphere_center_radius(s)        # dict {center,radius} OR list [x,y,z,r]
                        if c is not None:
                            out.append({"link": str(link), "center": c, "radius": r})
                        else:
                            skipped += 1
                # diagnostic: n parsed + (if 0) why, so the operator/agent can see the mismatch
                resp = {"spheres": out, "n": len(out)}
                if not out:
                    resp["error"] = ("collision_spheres.yml has no parseable spheres "
                                     f"(found_links={len(cs)}, skipped_malformed={skipped}). "
                                     "Expected link -> [{center:[x,y,z], radius:r}] or [x,y,z,r].")
                self._json(resp)
            except Exception as e:  # noqa: BLE001
                self._json({"spheres": [], "error": f"{type(e).__name__}: {e}"})
            return
        # The spheres gate's CHECK report (per-link coverage metrics + the self-collision audit
        # verdict + named phantom pairs) the agent writes alongside collision_spheres.yml. The Studio
        # renders it so the operator approves on evidence, not by eyeballing.
        if path == "/project/spheres/report" and self.command == "GET":
            f = PROJECT / "remoroo_cell" / "robot_model" / "spheres_report.json"
            if not f.exists():
                self._json({}); return
            try:
                self._json(json.loads(f.read_text()))
            except Exception as e:  # noqa: BLE001
                self._json({"error": f"{type(e).__name__}: {e}"})
            return
        # Live progress of the (slow, on-edge) MorphIt fit — the agent writes {link_i, n, link} per
        # link so the gate shows "fitting 12/30" instead of a hung window. Stale once the fit finishes.
        if path == "/project/spheres/progress" and self.command == "GET":
            f = PROJECT / "remoroo_cell" / "robot_model" / "spheres_progress.json"
            if not f.exists():
                self._json({}); return
            try:
                self._json(json.loads(f.read_text()))
            except Exception as e:  # noqa: BLE001
                self._json({"error": f"{type(e).__name__}: {e}"})
            return
        # Serve the PERSISTED model (robot_model/robot.urdf) + its meshes so the
        # studio can AUTOLOAD the full geometry from the repo on reopen — instead
        # of losing the URDF/meshes (blobs are in-browser only).
        if path == "/project/modelurdf" and self.command == "GET":
            f = PROJECT / "remoroo_cell" / "robot_model" / "robot.urdf"
            if not f.exists():
                self._json({"error": "no model"}, 404); return
            text = f.read_bytes()
            self.send_response(200)
            self.send_header("Content-Type", "application/xml")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Content-Length", str(len(text)))
            self.end_headers(); self.wfile.write(text); return
        if path == "/project/meshlist" and self.command == "GET":
            mdir = PROJECT / "remoroo_cell" / "meshes"
            files = sorted(p.name for p in mdir.glob("*") if p.is_file()) if mdir.exists() else []
            self._json({"meshes": files}); return
        if path == "/project/mesh" and self.command == "GET":
            safe = Path((query.get("name") or [""])[0]).name  # basename only — no traversal
            f = PROJECT / "remoroo_cell" / "meshes" / safe
            if not safe or not f.exists() or not f.is_file():
                self.send_response(404); self.end_headers(); return
            data = f.read_bytes()
            self.send_response(200)
            self.send_header("Content-Type", MIME.get(f.suffix, "application/octet-stream"))
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Content-Length", str(len(data)))
            self.end_headers(); self.wfile.write(data); return
        # The operator's MODEL, persisted at the model gate: overlay robot_model/
        # robot.urdf + meshes/ into remoroo_cell/ so the agent + cuRobo consume the
        # complete URDF immediately. Overlay (extractall) — does NOT wipe other
        # artifacts (calibration/, world/, ...), unlike the full /project/export.
        if path == "/project/model" and self.command == "POST":
            length = int(self.headers.get("Content-Length", "0") or 0)
            raw = self.rfile.read(length)
            dest = PROJECT / "remoroo_cell"
            dest.mkdir(parents=True, exist_ok=True)
            try:
                with zipfile.ZipFile(io.BytesIO(raw)) as zf:
                    zf.extractall(dest)
            except Exception as e:  # noqa: BLE001
                self._json({"error": f"bad model bundle: {e}"}, 400)
                return
            self._json({"ok": True, "path": str(dest / "robot_model" / "robot.urdf")})
            return
        if path == "/project/export" and self.command == "POST":
            # OVERLAY the operator's model onto remoroo_cell/ — NEVER wipe it. The old code
            # rmtree'd the whole cell and replaced it with the bundle, DESTROYING the agent's
            # authored primitives.py / world/ / calibration/ (the cell-bundle data-loss bug).
            # extractall overlays the model files in place; everything else survives.
            length = int(self.headers.get("Content-Length", "0") or 0)
            raw = self.rfile.read(length)
            dest = PROJECT / "remoroo_cell"
            dest.mkdir(parents=True, exist_ok=True)
            try:
                with zipfile.ZipFile(io.BytesIO(raw)) as zf:
                    zf.extractall(dest)
            except Exception as e:  # noqa: BLE001
                self._json({"error": f"bad cell bundle: {e}"}, 400)
                return
            committed = git_commit(PROJECT, "remoroo_cell") if parse_qs(urlparse(self.path).query).get("commit") == ["1"] else False
            self._json({"ok": True, "path": str(dest), "committed": committed})
            return
        self._json({"error": "not found"}, 404)

    # ---- routing ----
    def _route(self):
        u = urlparse(self.path)
        return u.path, parse_qs(u.query)

    def _stale_run(self, p: str) -> bool:
        """In setup mode this studio server is pinned to ONE run (RUN_ID). A request for a
        DIFFERENT run's /runs/<id>/… is a STALE browser tab from a prior `remoroo setup`
        (still open, reconnecting, streaming its old run, polluting this run's state). Refuse
        it so stale tabs can't drive or corrupt the live run. Run CREATION is done by the CLI,
        never the SPA, so the SPA only ever addresses RUN_ID here."""
        if not RUN_ID or not p.startswith("/runs/"):
            return False
        parts = p.split("/")  # ['', 'runs', '<id>', ...]
        rid = parts[2] if len(parts) > 2 else ""
        if rid and rid != RUN_ID:
            if rid not in _STALE_RUNS_SEEN:
                _STALE_RUNS_SEEN.add(rid)
                print(f"[remoroo-studio] ignoring a stale browser tab bound to run {rid} "
                      f"(this studio serves run {RUN_ID}); close that old tab.", flush=True)
            self._json({"error": "stale run — this studio is bound to a different run", "current": RUN_ID}, 409)
            return True
        return False

    def do_GET(self):
        p, q = self._route()
        if p == "/health":
            self._json({"ok": True, "edge": "real" if EDGE_URL else "none", "brain": bool(BRAIN_URL), "run_id": RUN_ID})
        elif p == "/studio/whoami":
            # Auth self-check the SPA calls on boot → it can warn the operator
            # IMMEDIATELY if they're not authenticated, not after a failed save.
            ok, _info = auth_reason(q, self.headers)
            self._json({"authed": ok, "version": os.environ.get("STUDIO_VERSION", "")})
        elif p == "/studio/session":
            self._json({"run_id": RUN_ID, "edge": "real" if EDGE_URL else "none", "brain": bool(BRAIN_URL),
                        "version": os.environ.get("STUDIO_VERSION", "")})
        elif p == "/live/joints" or p.startswith("/edge/"):
            self._proxy(EDGE_URL) if EDGE_URL else self._json({"error": "edge not connected"}, 501)
        elif p.startswith("/runs/") or p.startswith("/agent/"):
            if self._stale_run(p):
                return
            self._proxy(BRAIN_URL, SESSION_KEY) if BRAIN_URL else self._json({"error": "no control plane"}, 501)
        elif p.startswith("/project/"):
            self._project(p, q)
        else:
            self._static(p, q)

    def do_POST(self):
        p, q = self._route()
        if p.startswith("/runs/") or p.startswith("/agent/"):
            if self._stale_run(p):
                return
            self._proxy(BRAIN_URL, SESSION_KEY) if BRAIN_URL else self._json({"error": "no control plane"}, 501)
        elif p.startswith("/control/edge"):
            self._control_edge(p, q)
        elif p.startswith("/edge/"):
            self._proxy(EDGE_URL) if EDGE_URL else self._json({"error": "edge not connected"}, 501)
        elif p.startswith("/project/"):
            self._project(p, q)
        else:
            self._json({"error": "not found"}, 404)

    def _control_edge(self, path: str, query: dict):
        """Operator edge lifecycle from the Studio: POST /control/edge/{restart|stop|start}. Drives
        the SAME pidfile-managed `remoroo edge` lifecycle the agent uses (so the running edge picks
        up an authored-code fix). Token-gated; runs on the robot where the edge lives."""
        if not token_ok(query, self.headers):
            self._json({"error": "token required"}, 401)
            return
        action = path.rstrip("/").rsplit("/", 1)[-1]
        if action not in ("restart", "stop", "start", "status"):
            action = "restart"
        try:
            from remoroo import edge_service  # studio_server runs under the CLI python → importable
        except Exception as e:  # noqa: BLE001
            self._json({"error": f"edge control unavailable: {e}"}, 501)
            return
        try:
            fn = {"restart": edge_service.restart, "stop": edge_service.stop, "start": edge_service.start}.get(action)
            if fn is not None:
                res = fn(PROJECT, echo=lambda s: print(f"[control] {s}", flush=True))
            else:
                res = edge_service.status(PROJECT)
            self._json({"ok": True, "action": action, "result": res})
        except Exception as e:  # noqa: BLE001
            self._json({"ok": False, "action": action, "error": f"{type(e).__name__}: {e}"}, 500)

    def do_PUT(self):
        p, q = self._route()
        if p.startswith("/project/"):
            self._project(p, q)
        else:
            self._json({"error": "not found"}, 404)


def main():
    PROJECT.mkdir(parents=True, exist_ok=True)
    url = f"http://{lan_ip()}:{PORT}/?token={TOKEN}"
    print(f"[remoroo-studio] {url}")
    print(f"[remoroo-studio] serving {DIST} · project {PROJECT}")
    print(f"[remoroo-studio] edge: {EDGE_URL or 'sim (client-side)'} · brain: {BRAIN_URL or 'sim agent'}")
    ThreadingHTTPServer(("0.0.0.0", PORT), Handler).serve_forever()


if __name__ == "__main__":
    main()
