"""apidump — the engine describes ITSELF in one command:

    python -m task_engine.apidump

Prints the complete authoring contract from the INSTALLED code (import paths, every
public signature, dataclass fields, service verbs). This is the drift-proof ground
truth: if the api seed ever disagrees with the installed version, ONE run of this
replaces any amount of module-by-module spelunking. CI regenerates it and diffs the
seed's import block against it (tests/test_seed_contract.py).
"""
from __future__ import annotations

import inspect
from dataclasses import fields, is_dataclass
from typing import Any, List


def _sigs(mod: Any, prefix: str = "") -> List[str]:
    out = []
    for name in sorted(vars(mod)):
        if name.startswith("_"):
            continue
        obj = vars(mod)[name]
        if inspect.isfunction(obj) and obj.__module__ == mod.__name__:
            try:
                out.append(f"{prefix}{name}{inspect.signature(obj)}")
            except (ValueError, TypeError):
                out.append(f"{prefix}{name}(...)")
    return out


def _methods(cls: Any, prefix: str) -> List[str]:
    out = []
    for name, obj in sorted(vars(cls).items()):
        if name.startswith("_") or not callable(obj):
            continue
        try:
            out.append(f"{prefix}{name}{inspect.signature(obj)}")
        except (ValueError, TypeError):
            out.append(f"{prefix}{name}(...)")
    return out


def _dc_fields(cls: Any) -> str:
    if not is_dataclass(cls):
        return ""
    return ", ".join(f.name for f in fields(cls))


def dump() -> str:
    from . import atoms, envelope, params, run_trial, trace
    from . import env as env_mod
    from .judge import v0 as judge_v0
    from .perceive import loaders, operators, serving
    from .scene import state as scene_state
    from .service import BRIDGE_VERBS, TaskService

    L: List[str] = ["# task_engine contract (generated by `python -m task_engine.apidump`)"]

    L.append("\n## imports that exist (copy these exactly)")
    L += [
        "from task_engine import atoms                      # the 11 atoms",
        "from task_engine.env import GenericEnv",
        "from task_engine.envelope import Envelope, EnvelopeViolation",
        "from task_engine.params import Knobs",
        "from task_engine.trace import Trace",
        "from task_engine.scene.state import SceneState, Entity, FeatureChannel",
        "from task_engine.judge.v0 import Verdict",
        "from task_engine.perceive.operators import PerceptionOps",
        "from task_engine.perceive.serving import ModelRegistry",
        "from task_engine.perceive.loaders import register_default_models, models_status",
        "from task_engine.run_trial import run_trial, TrialBudget",
    ]

    L.append("\n## atoms")
    L += _sigs(atoms)
    L.append("Ctx fields: " + _dc_fields(atoms.Ctx))

    L.append("\n## env")
    L.append("GenericEnv fields: " + _dc_fields(env_mod.GenericEnv))
    L += _methods(env_mod.GenericEnv, "GenericEnv.")

    L.append("\n## params / envelope / trace")
    L += _methods(params.Knobs, "Knobs.")
    L += _methods(envelope.Envelope, "Envelope.")
    L += _methods(trace.Trace, "Trace.")

    L.append("\n## scene")
    for cls in (scene_state.SceneState, scene_state.Entity, scene_state.FeatureChannel):
        L.append(f"{cls.__name__} fields: {_dc_fields(cls)}")
    L += _methods(scene_state.SceneState, "SceneState.")

    L.append("\n## perceive")
    L += _methods(operators.PerceptionOps, "PerceptionOps.")
    L += _methods(serving.ModelRegistry, "ModelRegistry.")
    L += _sigs(loaders, "loaders.")

    L.append("\n## judge.v0")
    L += _sigs(judge_v0)
    L.append("Verdict fields: " + _dc_fields(judge_v0.Verdict))

    L.append("\n## trials + service")
    L += _sigs(run_trial)
    verbs = sorted(n[2:] for n in vars(TaskService) if n.startswith("v_"))
    L.append("edge verbs (/edge/task/<verb>): " + ", ".join(verbs))
    L.append("BRIDGE_VERBS (serialized under the bridge lock): "
             + ", ".join(sorted(BRIDGE_VERBS)))
    return "\n".join(L)


def main() -> None:
    print(dump())


if __name__ == "__main__":
    main()
